### PR TITLE
Fail on no captures

### LINKED ISSUE #44: Detect if there are no captures in query?
Not sure if there's a "provided" way to achieve this?

### PR DESCRIPTION
**Pull request by helixbass**
In this PR:
- fail "nicely" if the provided query contains no captures

Closes #44 

To test:
If you try passing a query with no captures in it eg `-q (function_item)` then it should print an error message (only once) that there must be at least one capture in the query and then exit with an error status code

Based on `byte-offset`

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -47,18 +47,27 @@ struct CaptureIndex(OnceLock<Result<u32, ()>>);
...
+        let mut failure_message: Option<String> = Default::default();
         self.0
             .get_or_init(|| match capture_name {
-                None => Ok(0),
+                None => match query.capture_names().len() {
+                    0 => {
+                        failure_message = Some(
+                            "query must include at least one capture (\"@whatever\")".to_owned(),
+                        );
+                        #[allow(clippy::unit_arg)]
```
Comment (peterstuart) [inline src/lib.rs:58]: I looked up this link but I don't really understand what it's flagging here.

**Review by peterstuart — APPROVED** [review]

File: src/lib.rs (hunk 1 above)
Comment (helixbass) [reply src/lib.rs:58]: Apparently it dislikes using something other than a literal `()` to say "`()`" but I didn't bother reading its explanation why it doesn't like that (sounded like it was something about a likely syntax mistake which is not the case here)

(and here I'm using `Default::default()` to mean `()`, because I am liking using `Default::default()` where it conceptually applies)

(stepping back a little bit, I'm not sure why I'm using `Result<_, ()>` here which smells like just an `Option<_>`, but that's how it already was and I saw that I was using `Default::default()` for the `()` elsewhere here so mimicked that)
